### ISSUE TITLE
upgrade Cesium -- frustrum fixes

### ISSUE THREAD

**Issue by shentonfreude** [koansys/isat#47]
Maybe also fix for multi-collection pickign?

**Comment by shentonfreude** [comment]
Woah, lots of changes in the tile providers breaking my code completely

```
Uncaught DeveloperError: target is required
Error
    at new DeveloperError (http://localhost/~cshenton/sot/viz/Cesium.js:372:22)
    at Camera.lookAt (http://localhost/~cshenton/sot/viz/Cesium.js:53223:19)
    at http://localhost/~cshenton/sot/viz/index.js:309:23
    at http://localhost/~cshenton/sot/viz/index.js:347:2 
```
